on:
  push:
    branches: [ master ]
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose up
      run: docker-compose up -d
    - name: Check running containers
      run: docker-compose ps -a
    - name: Check logs
      run: docker-compose logs app
    - name: Test with pytest
      run: docker-compose exec -T app pytest
